### ISSUE TITLE
How can I receive multiple generated images in TouchDesigner when the batch size is set to more than 1?

### ISSUE THREAD

**Issue by KeitoTakaishi** [olegchomp/TouchDiffusion#1]
HI, thanks for nice work!
How can I receive multiple generated images in TouchDesigner when the batch size is set to more than 1?

**Comment by olegchomp** [comment]
Hi, you can start from this point. 
https://github.com/olegchomp/TouchDiffusion/blob/317e08fa34bf2beb0ab99953e7f8b00d2a406f9a/TouchDiffusionExt.py#L63-L70
