### ISSUE TITLE
Module compilation error

### ISSUE THREAD

**Issue by zhenlyzheng** [olegchomp/TouchDiffusion#11]
TouchDesigner  Build 2023.11760 compile on Fri May  3 06:58:38 2024
Python 3.11.1 (heads/3.11-Derivative-dirty:82b0389147, Jan 25 2023, 22:34:27) [MSC v.1929 64 bit (AMD64)]

Added 'TouchDiffusion-main\.venv/Lib/site-packages' to sys.path.
Warning: 'TouchDiffusion-main\embedded_python/Lib/site-packages' is not a valid directory.
Added 'TouchDiffusion-main\StreamDiffusion/src' to sys.path.
Added 'TouchDiffusion-main' to sys.path.
DAT compile error: /project1/TouchDiffusion/TouchDiffusionExt
Traceback (most recent call last):
  File "/project1/TouchDiffusion/TouchDiffusionExt", line 4
    r = previousimport(*args, **kw)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\TouchDiffusion-main\.venv/Lib/site-packages\torch\__init__.py", line 451
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.

Error retrieving extension for /project1/TouchDiffusion: (Extension 1) td.tdError: Module compilation error. See /project1/TouchDiffusion/TouchDiffusionExt for details.
python >>> 

**The select engine can't be used, click the refresh engines  "pulse" ,doesn't get any response.**

**Comment by olegchomp** [comment]
1) check your TD settings, sight packages menu should be empty.
2) you main Python environment might have torch installed in it 
3) Try with portable version
