### ISSUE TITLE
Unable to load engine

### ISSUE THREAD

**Issue by RP335** [olegchomp/TouchDiffusion#12]
Made engines following the steps in the video. I'm on mac m1 and had to disable cuda for building engines. I built it with the dreamshaper_8 model and got this output:
<img width="729" alt="image" src="https://github.com/user-attachments/assets/9fb2b36e-5773-40af-85e0-ef1ff7b7189d">
After this, I followed the remaining steps to add the .tox file into my project and added the folder path to TouchDiffusion folder
However, once I'm done adding this, I get an error when clicking Refresh Engines:
<img width="470" alt="image" src="https://github.com/user-attachments/assets/d1c5992d-4200-4579-ba07-0525c0348189">

**Comment by olegchomp** [comment]
There is no Mac support, cause CUDA dependencies hardcoded.
