### ISSUE TITLE
No module named 'torch' 

### ISSUE THREAD

**Issue by sammyjank** [olegchomp/TouchDiffusion#13]
After going through the manual installation process, I got the following error message in CMD, just right before hitting the make engine step:
An unexpected error occurred while executing the command: No module named 'torch'

However, the webui said that it was finished installing. 

Jumping on the next step, which is loading the default SD turbo model and making the engine, gave me those dll errors, you have in your tutorial, while installing.  I  let the process running anyway which again bumped into a horde of new messages:
[W:onnxruntime:, constant_folding.cc:212 onnxruntime::ConstantFolding::ApplyImpl] Could not find a CPU kernel and hence can't constant fold Sqrt node '/down_blocks.0/attentions.0/transformer_blocks.0/attn1/Sqrt'.

Regardless, it could finish building the engine and everything is working. Just wondering whether things mentioned above could affect anything, or these outputs are normal. For instance, dreamshaper_8 model gives me those  blobby, blurry, hazy images... 

Thanks for putting this project together!

**Comment by olegchomp** [comment]
This might be something with your main python, like torch installed in it or something else. If it works it ok, cause otherwise it won't work at all
