### ISSUE TITLE
CAN'T GENERATE ENGINE

### ISSUE THREAD

**Issue by Sept-faeyza** [olegchomp/TouchDiffusion#14]
I tried generating the engine on the local host, but I encountered an error, which said "name 'StreamDiffusionWrapper' is not defined"
Please help to solve the problem, thank you
![Screenshot (39)](https://github.com/user-attachments/assets/2588f8de-c31c-43f9-aa86-de449f1ed895)
![Screenshot (40)](https://github.com/user-attachments/assets/358f93d9-ba9e-489f-bdef-91b81109faec)

**Comment by abelbrata** [comment]
I got the same error

**Comment by olegchomp** [comment]
Might be something with model or broken installation. Better to try with portable version

**Comment by Sept-faeyza** [comment]
> Might be something with model or broken installation. Better to try with portable version

ok,, oleg

**Comment by Sept-faeyza** [comment]
> Might be something with model or broken installation. Better to try with portable version

Hi Oleg, I've tried the portable version, and it works, I managed to install the engine, but when I continued with the Touch Designer process I experienced problems, my TouchDesigner Component file couldn't open the engine.


![image](https://github.com/user-attachments/assets/dd3969e3-d0f4-4d9f-a4e5-b28bf710c957)
![image](https://github.com/user-attachments/assets/d1eec1a9-e49f-4932-9daf-e9587e86ddaf)
![image](https://github.com/user-attachments/assets/f26c118f-118e-4932-9dcc-b61968aca3fd)

**Comment by Sept-faeyza** [comment]
> > Might be something with model or broken installation. Better to try with portable version
> 
> Hi Oleg, I've tried the portable version, and it works, I managed to install the engine, but when I continued with the Touch Designer process I experienced problems, my TouchDesigner Component file couldn't open the engine.
> 
> ![image](https://private-user-images.githubusercontent.com/113542882/353712671-dd3969e3-d0f4-4d9f-a4e5-b28bf710c957.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MDYxNjIsIm5iZiI6MTcyMjQwNTg2MiwicGF0aCI6Ii8xMTM1NDI4ODIvMzUzNzEyNjcxLWRkMzk2OWUzLWQwZjQtNGQ5Zi1hNGU1LWIyOGJmNzEwYzk1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwNjA0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2RmNzFkOWZkNGVlYzIwZjU1YTQ2Yjk1Y2ZjOTAyNWIwY2U2YzU5MjRmZDFkY2I4ZDgwZTA0YzljZmJjNzc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yFNBbtB8HWORb1E-KeFoDWB3j2BT_dhNt6ezxqmuidg) ![image](https://private-user-images.githubusercontent.com/113542882/353712787-d1eec1a9-e49f-4932-9daf-e9587e86ddaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MDYxNjIsIm5iZiI6MTcyMjQwNTg2MiwicGF0aCI6Ii8xMTM1NDI4ODIvMzUzNzEyNzg3LWQxZWVjMWE5LWU0OWYtNDkzMi05ZGFmLWU5NTg3ZTg2ZGRhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwNjA0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzVlZTdjZDI3ZTM1MTBlYjc5OGE0NzQ2NjhmODk2MmQ4ZTRiMzlmZTBlZDQzYjk5YzBiNWYzN2VlMzFkZWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ITPg_W7YF6X2MWy_oYyL7r6byooFdjFRNpZRiVnMxBE) ![image](https://private-user-images.githubusercontent.com/113542882/353712945-f26c118f-118e-4932-9dcc-b61968aca3fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MDYxNjIsIm5iZiI6MTcyMjQwNTg2MiwicGF0aCI6Ii8xMTM1NDI4ODIvMzUzNzEyOTQ1LWYyNmMxMThmLTExOGUtNDkzMi05ZGNjLWI2MTk2OGFjYTNmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwNjA0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDY1NTZiNmZhMzMxYzE3NTEwNGI1MmM2MWE5NTFmNGNiYzEzZmY3MzQ0NjA0MmRkZTk3NGM5NDgzNjUxMzcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AAnIzrxFYlhMrp8o0PkEYcBtZnU9bdMi1gnYpzQ_GFQ)

what should i do??

**Comment by Sept-faeyza** [comment]
> > > Might be something with model or broken installation. Better to try with portable version
> > 
> > 
> > Hi Oleg, I've tried the portable version, and it works, I managed to install the engine, but when I continued with the Touch Designer process I experienced problems, my TouchDesigner Component file couldn't open the engine.
> > ![image](https://private-user-images.githubusercontent.com/113542882/353712671-dd3969e3-d0f4-4d9f-a4e5-b28bf710c957.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MDYxNjIsIm5iZiI6MTcyMjQwNTg2MiwicGF0aCI6Ii8xMTM1NDI4ODIvMzUzNzEyNjcxLWRkMzk2OWUzLWQwZjQtNGQ5Zi1hNGU1LWIyOGJmNzEwYzk1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwNjA0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2RmNzFkOWZkNGVlYzIwZjU1YTQ2Yjk1Y2ZjOTAyNWIwY2U2YzU5MjRmZDFkY2I4ZDgwZTA0YzljZmJjNzc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yFNBbtB8HWORb1E-KeFoDWB3j2BT_dhNt6ezxqmuidg) ![image](https://private-user-images.githubusercontent.com/113542882/353712787-d1eec1a9-e49f-4932-9daf-e9587e86ddaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MDYxNjIsIm5iZiI6MTcyMjQwNTg2MiwicGF0aCI6Ii8xMTM1NDI4ODIvMzUzNzEyNzg3LWQxZWVjMWE5LWU0OWYtNDkzMi05ZGFmLWU5NTg3ZTg2ZGRhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwNjA0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzVlZTdjZDI3ZTM1MTBlYjc5OGE0NzQ2NjhmODk2MmQ4ZTRiMzlmZTBlZDQzYjk5YzBiNWYzN2VlMzFkZWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ITPg_W7YF6X2MWy_oYyL7r6byooFdjFRNpZRiVnMxBE) ![image](https://private-user-images.githubusercontent.com/113542882/353712945-f26c118f-118e-4932-9dcc-b61968aca3fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MDYxNjIsIm5iZiI6MTcyMjQwNTg2MiwicGF0aCI6Ii8xMTM1NDI4ODIvMzUzNzEyOTQ1LWYyNmMxMThmLTExOGUtNDkzMi05ZGNjLWI2MTk2OGFjYTNmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwNjA0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDY1NTZiNmZhMzMxYzE3NTEwNGI1MmM2MWE5NTFmNGNiYzEzZmY3MzQ0NjA0MmRkZTk3NGM5NDgzNjUxMzcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AAnIzrxFYlhMrp8o0PkEYcBtZnU9bdMi1gnYpzQ_GFQ)
> 
> what should i do??

My destination folder is correct, it matches the folder containing the web.ui file

**Comment by zaharbaz** [comment]
Same issue for me.

Pytorch reinstalled and updated


![image](https://github.com/user-attachments/assets/cae2429f-c584-4d1e-a8d7-05c7b803697b)
![image](https://github.com/user-attachments/assets/15caf1a7-787b-43cb-b684-616c74e27a5b)

**Comment by olegchomp** [comment]
@zaharbaz try with Portable version, also check that TD version is 2023

**Comment by zaharbaz** [comment]
The issue is fixed. 
It was conflict with pytorch on my system. After uninstall pytorch from my system's Python, the error is gone.
Command what I used for uninstall: `pip uninstall torch`

**Comment by Nahdra** [comment]
> The issue is fixed. It was conflict with pytorch on my system. After uninstall pytorch from my system's Python, the error is gone. Command what I used for uninstall: `pip uninstall torch`

I have the same issue, can you briefly tell me step by step to do this? Thanks !

**Comment by olegchomp** [comment]
> > The issue is fixed. It was conflict with pytorch on my system. After uninstall pytorch from my system's Python, the error is gone. Command what I used for uninstall: `pip uninstall torch`
> 
> I have the same issue, can you briefly tell me step by step to do this? Thanks !

Open TouchDesigner settings and remove path from "site-packages"
