### ISSUE TITLE
ModelNotFoundError: no module named 'torch' in Touchdesigner

### ISSUE THREAD

**Issue by sirgu** [olegchomp/TouchDiffusion#16]
Hi there! Installed everything without any major errors but now when getting in TD I have this error, in the attached screenshot

What should I do?[](url)
![TDiffusion_Error](https://github.com/user-attachments/assets/a86013c8-3fd6-4cf3-b481-55cf6245951a)

**Comment by olegchomp** [comment]
1. check your TD settings, sight packages menu should be empty.
2. Your main Python environment might have torch installed in it
3. Try with portable version

**Comment by sirgu** [comment]
hey thx for the fast reply and sorry for my nooby qs! didnt got it:

1. What TD settings? Touch Diffusion or Touch Desinger, either I dont get it what sight packages are?

2. Torch looks as it would be not installed:

C:\Users\info>python
Python 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'
>>> print(torch.__version__
... import torch
  File "<stdin>", line 2
    import torch
    ^^^^^^
SyntaxError: invalid syntax
>>> print(torch.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'torch' is not defined
>>>

3. Portable Git version? do you mean that? or what portable version?
Lets solve this ;) ;)

**Comment by sirgu** [comment]
Thx for the fast replay!!
1. dont know which TD settings (Touch Designer / Touch Diffusion?) and what is a sight package?

2. Python Torch looks not installed!

C:\Users\info>python
Python 3.11.8 (tags/v3.11.8:db85d51, Feb 6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

            import torch
            Traceback (most recent call last):
            File "", line 1, in
            ModuleNotFoundError: No module named 'torch'
            print(torch.version
            ... import torch
            File "", line 2
            import torch
            ^^^^^^
            SyntaxError: invalid syntax
            print(torch.version)
            Traceback (most recent call last):
            File "", line 1, in
            NameError: name 'torch' is not defined



3. I try now with portable TouchDiffusion! ;)

**Comment by sirgu** [comment]
ok portable works! very stable! thanks for your reply! AMAZINGly Insane!
