### ISSUE TITLE
TouchDesigner crashes

### ISSUE THREAD

**Issue by MelancholicMachinery** [olegchomp/TouchDiffusion#3]
Dear Oleg,
I followed your instructions, but TouchDesigner crashes if I press any of the buttons (Refresh engines, Clear Log, Re-init).
Also the tox shows an Error (its a long error message but it says that "lumpy.core.multiarray failed to import"
Thank you for your help.

**Comment by olegchomp** [comment]
Double check that you have python 3.11 & TouchDesigner 2023

**Comment by olegchomp** [comment]
> the log shows:cannot access local variable 'pipe' where it is not associated with a value

1) Restart TD
2) Press ALT + T
3) Copy log here

**Comment by itsleon21** [comment]
> > the log shows:cannot access local variable 'pipe' where it is not associated with a value
> 
> 1. Restart TD
> 2. Press ALT + T
> 3. Copy log here

TouchDesigner  Build 2023.11600 compile on Tue Mar  5 01:21:01 2024
Python 3.11.1 (heads/3.11-Derivative-dirty:82b0389147, Jan 25 2023, 22:34:27) [MSC v.1929 64 bit (AMD64)]

Added 'E:/DL/TD practise/TouchDiffusion-main\.venv/Lib/site-packages' to sys.path.
Added 'E:/DL/TD practise/TouchDiffusion-main\StreamDiffusion/src' to sys.path.
Added 'E:/DL/TD practise/TouchDiffusion-main' to sys.path.
DAT compile warnings: /project1/TouchDiffusion/TouchDiffusionExt
E:\DL/TD practise/TouchDiffusion-main\.venv/Lib/site-packages\diffusers\models\transformers\transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
512 512
Model load has failed. Doesn't exist.
cannot import name 'packaging' from 'pkg_resources' (C:\Users/admin/AppData/Local/Programs/Python/Python311/Lib/site-packages\pkg_resources\__init__.py)
Loading pipeline components...:   0%|          | 0/6 [00:00<?, ?it/s]Some weights of the model checkpoint were not used when initializing CLIPTextModel: 
 ['text_model.embeddings.position_ids']
Loading pipeline components...:  83%|########3 | 5/6 [00:00<00:00, 33.30it/s]
Loading pipeline components...: 100%|##########| 6/6 [00:00<00:00, 35.74it/s]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
C:\Users/admin/AppData/Local/Programs/Python/Python311/Lib/site-packages\_distutils_hack\__init__.py:11: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
C:\Users/admin/AppData/Local/Programs/Python/Python311/Lib/site-packages\_distutils_hack\__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
python >>>

**Comment by olegchomp** [comment]
@itsleon21 try with portable version

**Comment by itsleon21** [comment]
> @itsleon21 try with portable version

it worked! But still have some issues and the result looks blur and wierd.The log shows:

Keyword arguments {'add_watermarker': False} are not expected by StableDiffusionPipeline and will be ignored.
Loading pipeline components...:   0%|          | 0/5 [00:00<?, ?it/s]
Loading pipeline components...:  40%|####      | 2/5 [00:00<00:00, 12.31it/s]
Loading pipeline components...: 100%|##########| 5/5 [00:00<00:00, 15.84it/s]
Loading pipeline components...: 100%|##########| 5/5 [00:00<00:00, 15.31it/s]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
The config attributes {'skip_prk_steps': True} were passed to LCMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.

**Comment by itsleon21** [comment]
> @itsleon21 try with portable version

thank you very much!
